In [2]:
print('I will have the highest average in the class in accounting and mathematics.')

I will have the highest average in the class in accounting and mathematics.

In [3]:
'''
    7) Criação de Features: Crie uma nova coluna baseada em condições lógicas ou cálculos entre colunas existentes (ex: uma coluna "Margem de Lucro" baseada em "Preço" e "Custo").
'''

'\n    7) Criação de Features: Crie uma nova coluna baseada em condições lógicas ou cálculos entre colunas existentes (ex: uma coluna "Margem de Lucro" baseada em "Preço" e "Custo").\n'

In [5]:
# Importação da biblioteca seaborn
import seaborn as sns

# Carrega o dataset interno 'titanic'
df = sns.load_dataset('titanic')

df.head() # Mostra as 5 primeiras linhas do 'titanic'

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
# Feature: FamilySize
import pandas as pd

# Cria a feature usando Operações Aritméticas Simples
df['FamilySize'] = df['sibsp'] + df['parch'] + 1

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,FamilySize
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

In [11]:
# Featrure: IsAlone
import numpy as np

# Se FamilySize for 1, IsAlone recebe 1, caso contrário recebe 0
df['IsAlone'] = np.where(df['FamilySize'] > 1, 0, 1)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,FamilySize,IsAlone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1,1

In [14]:
# Feature: AgeGroup
# Usando o método .apply() com Funções
def categorizar_idade(idade):
    if idade < 12:
        return 'Criança'
    elif idade < 18:
        return 'Adolescente'
    else:
        return 'Adulto'

df['AgeGroup'] = df['age'].apply(categorizar_idade)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,FamilySize,IsAlone,AgeGroup
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2,0,Adulto
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,0,Adulto
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1,1,Adulto
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2,0,Adulto
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1,1,Adulto